version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      - GO111MODULE: on
      - GOLANG_VERSION: 1.13.6
    working_directory: /home/circleci/reaper-client-go
    steps:
      - run:
          name: install golang
          command: |
            GOROOT=$(go env GOROOT)
            sudo rm -r $(go env GOROOT)
            sudo mkdir $GOROOT
            echo "Installing Go ${GOLANG_VERSION}"
            curl https://dl.google.com/go/go${GOLANG_VERSION}.linux-amd64.tar.gz | sudo tar xz -C $GOROOT --strip-components=1
      - checkout
      - restore_cache:
          key: build-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/.go_workspace/pkg
      - run:
          name: run tests
          command: |
            export GO111MODULE=on
            make test
      - run:
          name: test cleanup
          command: |
            sudo chown -R circleci:circleci data/cassandra
            sudo chown -R circleci:circleci data/reaper
            make test-cleanup
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - reaper-client-go
      - save_cache:
          name: cache go modules
          key: build-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/.go_workspace/pkg
  release:
    docker:
      - image: circleci/golang:1.13
    working_directory: /home/circleci/reaper-client-go
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /home/circleci
      - run:
          name: publish release
          command: |
            go get github.com/tcnksm/ghr
            make publish-release
workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
