version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      - GO111MODULE: on
      - GOLANG_VERSION: 1.13.6
    working_directory: /home/circleci/reaper-client-go
    steps:
      - run:
          name: install golang
          command: |
            GOROOT=$(go env GOROOT)
            sudo rm -r $(go env GOROOT)
            sudo mkdir $GOROOT
            echo "Installing Go ${GOLANG_VERSION}"
            curl https://dl.google.com/go/go${GOLANG_VERSION}.linux-amd64.tar.gz | sudo tar xz -C $GOROOT --strip-components=1
      - checkout
      - restore_cache:
          key: build-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/.go_workspace/pkg
      - run:
          name: run tests
          command: |
            export GO111MODULE=on
            make test
      - save_cache:
          name: cache go modules
          key: build-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/.go_workspace/pkg
